Models/CarDescription.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ProjectPartB.Models
{
    public partial class CarDescription
    {
        public CarDescription()
        {
            CarAvailabilities = new HashSet<CarAvailability>();
           
        }

        public int CarDescriptionId { get; set; }
        public int? CarTypeId { get; set; }
        [Required(ErrorMessage = "The description is required.")]
        [StringLength(500, ErrorMessage = "The description cannot be longer than 500 characters.")]
        public string? Description { get; set; }
        [Required(ErrorMessage = "The brand is required.")]
        public string? Brand { get; set; }
        [Required(ErrorMessage = "The model is required.")]
        public string? Model { get; set; }
        [Required(ErrorMessage = "The color is required.")]
        public string? Color { get; set; }
        [Required(ErrorMessage = "The rate per day is required.")]
        [Range(0, 10000, ErrorMessage = "The rate per day must be between 0 and 10000.")]
        public decimal RatePerDay { get; set; }
        public bool? Available { get; set; }
        [Required(ErrorMessage = "Please upload an image.")]
        public string? Image { get; set; }
        [Required(ErrorMessage = "Please select the car type.")]
        public string CarTypeName { get; set; }
        public virtual CarType? CarType { get; set; }
        public virtual ICollection<CarAvailability> CarAvailabilities { get; set; }
        
    }
}

Controllers/CarDescriptionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using ProjectPartB.Models;
using X.PagedList;

namespace ProjectPartB.Controllers
{
    public class CarDescriptionsController : Controller
    {
        private readonly FS23_Group4_ProjectContext _context;
        private readonly IWebHostEnvironment _webHostEnviroment;

        public CarDescriptionsController(FS23_Group4_ProjectContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnviroment = webHostEnvironment;
        }


        //// GET: CarDescriptions
        //public async Task<IActionResult> Index()
        //{
        //    var fS23_Group4_ProjectContext = _context.CarDescriptions.Include(c => c.CarType);
        //    return View(await fS23_Group4_ProjectContext.ToListAsync());
        //}

        public IActionResult Index(string searchString, int? page, string sortOrder)
        {
            var pageNumber = page ?? 1;
            ViewData["NameSortParam"] = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            var carDescription = from e in _context.CarDescriptions select e;
            if (!string.IsNullOrEmpty(searchString))
            {
                carDescription = carDescription.Where(s => s.Brand.Contains(searchString));
            }
            //sort car by car availability
            carDescription = carDescription.OrderBy(s => s.Brand);
            switch (sortOrder)
            {
                case "name_desc":
                    carDescription = carDescription.OrderByDescending(s => s.Brand);
                    break;
            }
            //return View(await carDescription.ToListAsync());
            return View(carDescription.ToPagedList(pageNumber, 10));
        }
        public string IndexAJAX(string searchString)

        {

            string sql = "SELECT * FROM CarDescription WHERE Brand LIKE @p0";

            string wrapString = "%" + searchString + "%";

            List<CarDescription> carDescriptions = _context.CarDescriptions.FromSqlRaw(sql, wrapString).ToList();

            string jason = JsonConvert.SerializeObject(carDescriptions);

            return jason;

        }
        // GET: CarDescriptions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.CarDescriptions == null)
            {
                return NotFound();
            }

            var carDescription = await _context.CarDescriptions
                .Include(c => c.CarType)
                .FirstOrDefaultAsync(m => m.CarDescriptionId == id);
            if (carDescription == null)
            {
                return NotFound();
            }

            return View(carDescription);
        }
        [Authorize(Roles = "Administrator,Editor")]
        // GET: CarDescriptions/Create
        public IActionResult Create()
        {
            ViewData["CarTypeName"] = new SelectList(_context.CarTypes, "Name", "Name");
            return View();
        }
        [Authorize(Roles = "Administrator,Editor")]
        // POST: CarDescriptions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CarDescriptionId,CarTypeId,Description,Brand,Model,Color,RatePerDay,Available,Image,CarTypeName")] CarDescription carDescription, IFormFile image)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    string uploadFolder = Path.Combine(_webHostEnviroment.WebRootPath, "uploads");
                    string uniqueName = Guid.NewGuid().ToString() + "_" + image.FileName;
                    string filePath = Path.Combine(uploadFolder, uniqueName);
                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        await image.CopyToAsync(fileStream);

                    }
                    carDescription.Image = uniqueName;
                }
                _context.Add(carDescription);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CarTypeName"] = new SelectList(_context.CarTypes, "Name", "Name", carDescription.CarTypeName);
            return View(carDescription);
        }

        // GET: CarDescriptions/Edit/5
        [Authorize(Roles = "Administrator,Editor")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.CarDescriptions == null)
            {
                return NotFound();
            }

            var carDescription = await _context.CarDescriptions.FindAsync(id);
            if (carDescription == null)
            {
                return NotFound();
            }
            ViewData["CarTypeName"] = new SelectList(_context.CarTypes, "Name", "Name", carDescription.CarTypeName);
            return View(carDescription);
        }
        [Authorize(Roles = "Administrator,Editor")]
        // POST: CarDescriptions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CarDescriptionId,CarTypeId,Description,Brand,Model,Color,RatePerDay,Available,Image,CarTypeName")] CarDescription carDescription, IFormFile image)
        {
            if (id != carDescription.CarDescriptionId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    string uploadFolder = Path.Combine(_webHostEnviroment.WebRootPath, "uploads");
                    string uniqueName = Guid.NewGuid().ToString() + "_" + image.FileName;
                    string filePath = Path.Combine(uploadFolder, uniqueName);
                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        await image.CopyToAsync(fileStream);
                    }
                    carDescription.Image = uniqueName;
                }

                try
                {
                    _context.Update(carDescription);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CarDescriptionExists(carDescription.CarDescriptionId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }
            ViewData["CarTypeName"] = new SelectList(_context.CarTypes, "Name", "Name", carDescription.CarTypeName);
            return View(carDescription);
        }


        // GET: CarDescriptions/Delete/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.CarDescriptions == null)
            {
                return NotFound();
            }

            var carDescription = await _context.CarDescriptions
                .Include(c => c.CarType)
                .FirstOrDefaultAsync(m => m.CarDescriptionId == id);
            if (carDescription == null)
            {
                return NotFound();
            }

            return View(carDescription);
        }
        [Authorize(Roles = "Administrator")]
        // POST: CarDescriptions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.CarDescriptions == null)
            {
                return Problem("Entity set 'FS23_Group4_ProjectContext.CarDescriptions'  is null.");
            }
            var carDescription = await _context.CarDescriptions.FindAsync(id);
            if (carDescription != null)
            {
                _context.CarDescriptions.Remove(carDescription);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CarDescriptionExists(int id)
        {
            return (_context.CarDescriptions?.Any(e => e.CarDescriptionId == id)).GetValueOrDefault();
        }
       

    }
}

Views/CarDescriptions/Create.cshtml
@model ProjectPartB.Models.CarDescription

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>CarDescription</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CarTypeName" class="control-label"></label>
                <select asp-for="CarTypeName" class="form-control" asp-items="ViewBag.CarTypeName"></select>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Brand" class="control-label"></label>
                <input asp-for="Brand" class="form-control" />
                <span asp-validation-for="Brand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Model" class="control-label"></label>
                <input asp-for="Model" class="form-control" />
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Color" class="control-label"></label>
                <input asp-for="Color" class="form-control" />
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RatePerDay" class="control-label"></label>
                <input asp-for="RatePerDay" class="form-control" />
                <span asp-validation-for="RatePerDay" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" type="file" accept="image/jpeg,image/png" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/CarDescriptions/Delete.cshtml
@model ProjectPartB.Models.CarDescription

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CarDescription</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Brand)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Brand)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Model)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Model)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Color)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Color)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RatePerDay)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RatePerDay)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Available)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Available)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CarTypeName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CarTypeName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CarType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CarType.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CarDescriptionId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/CarDescriptions/Details.cshtml
@model ProjectPartB.Models.CarDescription

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>CarDescription</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Brand)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Brand)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Model)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Model)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Color)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Color)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RatePerDay)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RatePerDay)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Available)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Available)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            <img src="@Url.Content("~/uploads/"+ Model.Image)" alt="rental cars" width="160" height="150">
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CarTypeName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CarTypeName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CarType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CarType.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.CarDescriptionId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/CarDescriptions/Edit.cshtml
@model ProjectPartB.Models.CarDescription

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>CarDescription</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" asp-controller="CarDescriptions" method="post" enctype="multipart/form-data">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CarTypeName" />
            <div class="form-group">
                <label asp-for="CarTypeName" class="control-label"></label>
                <select asp-for="CarTypeName" class="form-control" asp-items="ViewBag.CarTypeName"></select>
                <span asp-validation-for="CarTypeName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                @*<input asp-for="ProductName" class="form-control" />*@
                <textarea asp-for="Description" cols="20" rows="3" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Brand" class="control-label"></label>
                <input asp-for="Brand" class="form-control" />
                <span asp-validation-for="Brand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Model" class="control-label"></label>
                <input asp-for="Model" class="form-control" />
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Color" class="control-label"></label>
                <input asp-for="Color" class="form-control" />
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RatePerDay" class="control-label"></label>
                <input asp-for="RatePerDay" class="form-control" />
                <span asp-validation-for="RatePerDay" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Available" class="control-label"></label>
                <input asp-for="Available" class="form-control" />
                <span asp-validation-for="Available" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" type="file" accept="image/jpeg,image/png" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CarTypeName" class="control-label"></label>
                <input asp-for="CarTypeName" class="form-control" />
                <span asp-validation-for="CarTypeName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
<script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/4.0.20/tinymce.min.js"></script>
<script type="text/javascript">
    tinymce.init({
        selector: 'textarea',
        plugins: "emoticons textcolor",
        toolbar: "undo redo styleselect bold italic emoticons forecolor backcolor fontselect",
        width: 600,
        height: 600,
        resize: 'both',
        placeholder: 'Type here...',
    });
</script>

Views/CarDescriptions/Index.cshtml
@model IPagedList<ProjectPartB.Models.CarDescription>
@using X.PagedList.Mvc.Core;
@using X.PagedList;
@using X.PagedList.Web.Common;
@{
    ViewData["Title"] = "Index";
}

<h1>Choose your car!!</h1>
@{
    // Check if the user is in the "Administrator" or "Visitor" role
    bool isUserAdminOrVisitor = User.IsInRole("Administrator") || User.IsInRole("Editor");
}@if (isUserAdminOrVisitor)
{
    <p>
        <a asp-action="Create">Create New</a>
    </p>
}
<form id="searchForm" action="/CarDescriptions/index" method="get">
    <p>Search Car Description</p>
    <input type="text" id="searchString" name="searchString" style="width:190px" autocomplete="off" onkeyup="AjaxRequest(this.value);" />
    <br />
    <div id="autoSuggestContainer" style="position:absolute; display:none;z-index:100;"></div>
    <input type="submit" value="Search" />

</form>
@Html.PagedListPager(Model, page => Url.Action("Index",new { Page = page }), new PagedListRenderOptions
{
LiElementClasses = new string[] { "page-item" },
PageClasses = new string[] { "page-link" }
})

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.First().Description)
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.First().ProductName)*@
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParam"]">@Html.DisplayNameFor(model => model.First().Brand)</a>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Model)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Color)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().RatePerDay)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Available)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Image)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().CarTypeName)
            </th>
          
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                    @Html.Raw(item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Brand)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Model)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Color)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RatePerDay)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Available)
            </td>
            <td>
                @*@Html.DisplayFor(modelItem => item.Image)*@
                <img src="@Url.Content("~/uploads/"+item.Image)" alt="rental cars" width="160" height="150">
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CarTypeName)
            </td>
            
            <td>
                <a asp-action="Edit" asp-route-id="@item.CarDescriptionId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.CarDescriptionId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.CarDescriptionId">Delete</a>
                <a asp-controller="ShoppingCart" asp-action="AddToCart" asp-route-id="@item.CarDescriptionId" class="btn btn-primary">Add To Cart</a>
            </td>
        </tr>
}
    </tbody>
</table>
<script type="text/javascript">
    function AjaxRequest(searchString) {
        if (searchString.length < 2) {
            document.getElementById("autoSuggestContainer").innerHTML = "";
            return;
        }
        //alert ("Testing searchString="+ searchString)
        var xmlhttp = new XMLHttpRequest();
        var url = "/CarDescriptions/indexAjax?searchString" + searchString;
        xmlhttp.open("GET", url, false);
        xmlhttp.send();
        document.getElementById("autoSuggestContainer").style.display = "block";

        //need to clear out the container for a fresh auto-suggest list

        //else the auto-suggest list can keep growing and growing with additional user keyups

        document.getElementById("autoSuggestContainer").innerHTML = "";



        var messageObject = JSON.parse(xmlhttp.responseText); // receive the respose text



        var autoSuggestions = "";



        for (var i = 0; i < messageObject.length; i++) {

            //HTML code generation demo

            //Works together with the ".innerHTML" statement after the end of this "for" block

            autoSuggestions +=

                "<input type=\"button\" value=\"" + messageObject[i].Brand + "\" "

                + "onclick=\"document.getElementById('searchString').value = this.value; document.getElementById('searchForm').submit();\" "

                + "style =\"width: 280px\" />";

            autoSuggestions += "<br />";

        }

        //place the generated buttons HTML code inside the display div

        document.getElementById("autoSuggestContainer").innerHTML = autoSuggestions;


    }
</script>